name: DDTVLiveRec_docker

on:
  push:
    branches:
      #- master
      - dockerhub

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prepare
        run: |
          VERSION=${{ github.event.client_payload.version }}
          [[ ! -n $VERSION ]] && VERSION=beta
          IMAGE_NAME=ddtvliverec
          TAGS_DEBIAN="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${VERSION}-Debian,${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest"
          TAGS_ALPINE="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${VERSION}-Alpine,${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest"
          echo ::set-output name=build_args::VERSION=${VERSION}
          echo ::set-output name=image-name::${IMAGE_NAME}
          echo ::set-output name=tags_debian::${TAGS_DEBIAN}
          echo ::set-output name=tags_alpine::${TAGS_ALPINE}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.debian
          platforms: linux/arm/v7
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags_debian }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags_alpine }}